analytics: {}
color:
  brandColors:
    - '#ADB7B6'
    - '#0C0805'
    - '#64361C'
    - '#DBA022'
    - '#007799'
  brandStrength: 0.336349
  lightness: 0.912346
  rhythmicContrast: 0.402397
  saturation: 0.477163
cta: {}
layout_spectrum: 0.98602
name: Bring Your Kid To Work Day
opengraph: {}
purpose: []
typography_spectrum: 0.347862
