analytics: {}
color:
  brandColors:
    - '#ADB7B6'
    - '#0C0805'
    - '#64361C'
    - '#DBA022'
    - '#007799'
  brandStrength: 0.144737
  lightness: 0.805921
  rhythmicContrast: 0.402397
  saturation: 0.269737
cta: {}
layout_spectrum: 1
name: Bring Your Kid To Work Day
opengraph: {}
purpose: []
typography_spectrum: 0.736842
