name: Bring Your Kid To Work Day
favicon: null
layout_spectrum: 0
typography_spectrum: 0.318257
title: Amazing Time
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADB7B6'
    - '#0C0805'
    - '#64361C'
    - '#DBA022'
    - '#007799'
  brandStrength: 0.336349
  lightness: 0.912346
  saturation: 0.477163
  rhythmicContrast: 0.402397
purpose: []
